using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameControllar : MonoBehaviour
{
    
    public static GameControllar instance;
    private const string HIGH_SCORE = "HighScore";
    private const string SELECTED_BIRD = "Selected Bird";

    private const string GREEN_BIRD = "Green Bird";
    private const string RED_BIRD = "Red Bird";

    

    void Start()
    {
                    
    }
     void Awake()
    {
        MakeSingleton();
        IsTheGameStartFormFirstTime();
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    void MakeSingleton()
    {
        instance = this;
        DontDestroyOnLoad(gameObject);
        //if (instance != null)
        //{
        //    Destroy(gameObject);
        //}
        //else
        //{
        //    instance = this;
        //    DontDestroyOnLoad(gameObject);
        //}
    }
    void IsTheGameStartFormFirstTime()
    {
        //PlayerPrefs.SetInt("High Score", 100);
        //PlayerPrefs.GetInt("High Score");
        if(!PlayerPrefs .HasKey ("IsTheGameStartFormFirstTime"))
        {
            PlayerPrefs.SetInt(HIGH_SCORE, 0);
            PlayerPrefs.SetInt(SELECTED_BIRD , 0);
            PlayerPrefs.SetInt(GREEN_BIRD , 1);
            PlayerPrefs.SetInt(RED_BIRD, 1);
            PlayerPrefs.SetInt("IsTheGameStartFormFirstTime", 0);

        }
    }
    public void SetHighScore(int score)
    {
        PlayerPrefs.SetInt(HIGH_SCORE, score);
    }
    public int GetHighScore()
    {
        return PlayerPrefs.GetInt(HIGH_SCORE);
    }
    public void SetSelectedBird(int selectedbird)
    {
        PlayerPrefs.SetInt(SELECTED_BIRD, selectedbird);
    }
    public int GetSelectedBird()
    {
        return PlayerPrefs.GetInt(SELECTED_BIRD);
    }
    public void UnlockGreenBird()
    {
        PlayerPrefs.SetInt(GREEN_BIRD, 1);
    }
    public int IsGreenBirdUnlocked()
    {
        return PlayerPrefs.GetInt(GREEN_BIRD);
    }
    public void UnlockRedBird()
    {
        PlayerPrefs.SetInt(RED_BIRD, 1);
    }
    public int IsRedBirdUnlocked()
    {
        return PlayerPrefs.GetInt(RED_BIRD);
    }
}

















